name: Release

on:
  push:
    tags:
      - 'v*'

env:
  FILE_NAME: rengo68-phi

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make sample ja files
        run: |
          mkdir $FILE_NAME-ja
          cp -r --parents main.typ README.md fig LICENSE.md  refs.yml .vscode lib.typ rengo.csl $FILE_NAME-ja
          zip -r $FILE_NAME-ja.zip $FILE_NAME-ja
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.FILE_NAME }}-ja.zip
          draft: true
          generate_release_notes: true
          body: |
            2025年の第68回 自動制御連合講演会用の要旨です。
            https://www.jsme.or.jp/conference/rengo68/
            Typst v0.13.1でコンパイルできます。
